version: '3.4'
x-logging:
      &default-logging
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
services:
  aada-finance:
<<<<<<<< HEAD:docker/development-testnet/docker-compose.yaml
    image: mantasand/aada-finance:development-testnet-latest
========
    container_name: aada-finance_aada-finance_1
    image: mantasand/aada-finance:release-testnet-latest
>>>>>>>> release-testnet:docker/release-testnet/docker-compose.yaml
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /gz/aada-app:/app/
    logging: *default-logging
