name: ci development-testnet branch

on:
  push:
    branches:
      - development-testnet

env:
  IMG_NAME: "mantasand/aada-finance"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:${{ github.ref_name }}-${{ github.run_id }},${{ env.IMG_NAME }}:${{ github.ref_name }}-latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.STAG_SERVER}}
          username: ${{secrets.STAG_USER}}
          key: ${{secrets.STAG_KEY}}
          port: ${{ secrets.STAG_PORT }}
          script: |

            cd /gz/aada-finance/
            git fetch
            git checkout -f ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            cd docker/${{ github.ref_name }}
            docker-compose pull
            docker-compose up -d

            sleep 5
            /gz/aada-finance/.ci/gen.sh ${{ github.ref_name }}
            export CARDANO_NODE_SOCKET_PATH=/gz/cardano/cardano-my-node/db/socket
            export VERSION=$(docker-compose exec -T aada-finance "compile-validators --version" | \
              cut -d '"' -f 2)
            /usr/bin/python3 /gz/aada-finance/.ci/version.py /gz/aada-finance/versions.json /gz/aada-app/${VERSION}/version_details.json $VERSION
            git add /gz/aada-finance/versions.json
            git commit -m "[skip ci] update versions from ci"
            git push origin ${{ github.ref_name }}
