name: ci dev branch

on:
  push:
    branches:
      - dev

env:
  IMG_NAME: "mantasand/aada-finance"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:dev-${{ github.run_id }},${{ env.IMG_NAME }}:dev-latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Deploy dev branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_SERVER}}
          username: ${{secrets.DEV_USER}}
          key: ${{secrets.DEV_KEY}}
          port: ${{ secrets.DEV_PORT }}
          script: |

            cd /gz/aada-finance/
            git fetch
            git checkout -f dev
            git reset --hard origin/dev

            cd docker/dev/
            docker-compose pull
            docker-compose up -d
