name: ci master branch

on:
  push:
    branches:
      - master

env:
  IMG_NAME: "mantasand/aada-finance"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:${{ github.ref_name }}-${{ github.run_id }},${{ env.IMG_NAME }}:${{ github.ref_name }}-latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |

            cd /gz/aada-finance/
            git fetch
            git checkout -f ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            cd docker/${{ github.ref_name }}
            docker-compose pull
            docker-compose up -d

            sleep 5
            docker-compose exec aada-finance compile-validators --hash 3e1d198908bbbe7fb4fae9b3c16037d61ea5f43c6d66bb89d0b369b1 -k
            docker-compose exec aada-finance mint-aada-nft minting-policy -l -p lender.nft
            docker-compose exec aada-finance mint-aada-nft minting-policy -b -p borrower.nft
